<?php $productsData = $this->getProductsData() ?>
<?php $widgetHelper = $this->helper('lipscore_ratingsreviews/widget'); ?>

<?php if ($productsData) { ?>
    <?php foreach ($productsData as $data) { ?>
        <div class="lipscore-purchase"
             ls-email="<?php echo $this->getCustomerEmail() ?>"
             ls-name="<?php echo $this->getCustomerName() ?>"
             ls-product-url="<?php echo $data['url'] ?>"
             ls-voucher-code="<?php echo $this->getCouponCode() ?>"
             ls-voucher-descr="<?php echo $this->getCouponDescription() ?>"
             <?php echo $widgetHelper->getProductAttrs($data)?>>
        </div>
    <?php } ?>
<?php } ?>
