<?php $productsData = $this->getProductsData() ?>

<?php if ($productsData) { ?>
    <?php foreach ($productsData as $data) { ?>
        <div class="lipscore-purchase"
             ls-email="<?php echo $this->getCustomerEmail() ?>"
             ls-name="<?php echo $this->getCustomerName() ?>"
             ls-product-name="<?php echo $data['name'] ?>" 
             ls-brand="<?php echo $data['brand'] ?>" 
             ls-sku="<?php echo $data['sku'] ?>"
             ls-product-id="<?php echo $data['internalId'] ?>"
             ls-product-url="<?php echo $data['url'] ?>"
             ls-voucher-code="<?php echo $this->getCouponCode() ?>"
             ls-voucher-descr="<?php echo $this->getCouponDescription() ?>">
        </div>
    <?php } ?>
<?php } ?>
