<?php
/**
 * JS block for lipscore initialization
 *
 * @see Mage_Core_Block_Template
 */
?>

<?php if ($this->isLipscoreActive && $this->lipscoreApiKey) { ?>
    <script data-cfasync="false" type="text/javascript">
    //<![CDATA[
    window.lipscoreInit = function() {
        lipscore.init({
            apiKey: "<?php echo $this->lipscoreApiKey ?>"
        });
    };
    (function() {
        var scr = document.createElement('script'); scr.async = 1; scr.setAttribute('data-cfasync', false);
        scr.charset = "utf-8";
        scr.src = "//<?php echo $this->assetsUrl ?>/<?php echo $this->getLipscoreLocale() ?>lipscore-v1.js";
        document.getElementsByTagName('head')[0].appendChild(scr);
    })();
    //]]>
    </script>
<?php } ?>
