<?php
/**
 * JS block for lipscore initialization
 *
 * @see Mage_Core_Block_Template
 */
?>

<script src="//<?php echo $this->assetsUrl ?>/<?php echo $this->getLipscoreLocale() ?>lipscore-v1.js"></script>
<link href="//<?php echo $this->assetsUrl ?>/lipscore-v1.css" rel="stylesheet" type="text/css">

<?php if ($this->lipscoreApiKey) { ?>
    <script type="text/javascript">
    //<![CDATA[
    window.lipscoreInit = function() {
        lipscore.init({
            apiKey: "<?php echo $this->lipscoreApiKey ?>"
        });
    };       
    //]]>
    </script>
<?php } ?>
