<div id="lipscore-richsnippet" 
    ls-rs-name=""
    ls-rs-brand=""
    ls-rs-description=""
    ls-rs-image=""
    ls-rs-product-id=""
    ls-rs-offer-price=""
    ls-rs-offer-currency=""
    ls-rs-offer-avaialbility=""
><div>

<p>
<?php echo 'Name: ' . $this->getRsName() ?><br/>
<?php echo 'Brand: ' . $this->getRsBrand() ?><br/>
<?php echo 'Descr: ' . $this->getRsDescription() ?><br/>
<?php echo 'Img: ' . $this->getRsImg() ?><br/>
<?php echo 'Id: ' . $this->getRsProductId() ?><br/>
<?php echo 'Price: ' . $this->getRsPrice() ?><br/>
<?php echo 'Currency: ' . $this->getRsCurrency() ?><br/>
<?php echo 'Avail.: ' . $this->getRsAvailability() ?><br/>
</p>