<div id="lipscore-richsnippet" 
    ls-description=""
    ls-image-url=""
    ls-price=""
    ls-price-currency=""
    ls-avaialbility=""
><div>

<p>
<?php echo 'Name: ' . $this->getRsName() ?><br/>
<?php echo 'Brand: ' . $this->getRsBrand() ?><br/>
<?php echo 'Descr: ' . $this->getRsDescription() ?><br/>
<?php echo 'Img: ' . $this->getRsImageUrl() ?><br/>
<?php echo 'Price: ' . $this->getRsPrice() ?><br/>
<?php echo 'Currency: ' . $this->getRsCurrency() ?><br/>
<?php echo 'Avail.: ' . $this->getRsAvailability() ?><br/>
</p>