<?php
/**
 * JS block for lipscore initialization
 *
 * @see Mage_Core_Block_Template
 */
?>

<?php $_apiKey = $this->helper('lipscore_ratingsreviews/init')->getLipscoreApiKey()  ?>

<?php if ($_apiKey) { ?>
    <script type="text/javascript">
    //<![CDATA[
    window.lipscoreInit = function() {
        lipscore.init({
            apiKey: "<?php echo $_apiKey ?>"
        });
    };       
    //]]>
    </script>
<?php } ?>
