<?php $_data = $this->helper('lipscore_ratingsreviews/product')->getProductData($this->getProduct())  ?>
<?php if ($_data) { ?>
    <div class="ratings mg-lipscore-rating-wrapper">
        <div <?php echo $this->getRatingType() ?>
             ls-product-name="<?php echo $_data['name'] ?>" 
             ls-brand="<?php echo $_data['brand'] ?>" 
             ls-sku="<?php echo $_data['sku'] ?>"
             ls-product-id="<?php echo $_data['internalId'] ?>">
        </div>
     </div>   
<?php } else { ?>
    <div style="display: none !important;">Lipscore: empty product data</div>
<?php } ?>
